=== MariaBoby2002/wsd_lab5/garage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:gb="http://www.example.com/garage"
           targetNamespace="http://www.example.com/garage"
           elementFormDefault="qualified">


    <xs:element name="garages">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="garage" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="location" type="xs:string"/>
                            <xs:element name="price" type="xs:decimal"/>
                            <xs:element name="availability" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== MariaBoby2002/wsd_lab5/garage.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="garage.xsl" type="text/xsl" ?> 
<garages
xmlns="http://www.example.com/garage"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.example.com/garage garage.xsd"
>

    <garage>
        <name>Central Garage</name>
        <location>Main Street, City</location>
        <price>25.00</price>
        <availability>Available</availability>
    </garage>
    <garage>
        <name>Downtown Garage</name>
        <location>2nd Avenue, City</location>
        <price>30.00</price>
        <availability>Not Available</availability>
    </garage>
    <garage>
        <name>Northside Garage</name>
        <location>North Road, City</location>
        <price>20.00</price>
        <availability>Available</availability>
    </garage>
</garages>
